# Generated by Django 4.0 on 2021-12-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='amt',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
