# Generated by Django 4.0 on 2021-12-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_alter_holding_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
