# Generated by Django 4.0 on 2021-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0003_holding_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
