# Generated by Django 4.0 on 2021-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0005_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='symbol',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
