# Generated by Django 4.0 on 2021-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0006_rate_symbol_rate_ticker_alter_rate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='ticker',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
