# Generated by Django 4.0 on 2022-01-05 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('holdings', '0007_alter_rate_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='users',
            field=models.ManyToManyField(through='holdings.Userrates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrates',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdings.rate'),
        ),
        migrations.AddField(
            model_name='userrates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
